kanbagis/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from kanbagisapp import views as kanbagisapp_views
from django.conf.urls import handler404, handler500

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('kanbagisapp.urls'))
]


admin.site.site_header = 'Kan Bağış Admin'
admin.site.index_title = 'Kan Bağışı'  
admin.site.site_title = 'Admin Sayfası'

kanbagisapp/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib import admin
from django.contrib.auth import views as auth_views
from kanbagisapp.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path
from .views import ThreadView, InboxView

urlpatterns = [
    url('^', include('django.contrib.auth.urls')),
    url(r'^home', views.home, name='home'),
    url(r'^icerik/(?P<id>\d+)/$', views.icerik, name='icerik'),
    url(r'^about', views.hakkimizda, name='hakkimizda'),
    url(r'^login/', auth_views.login, name='login'),
    url(r'^profile/(?P<username>\w+)/$', views.profile, name='profile'),
    url(r'^share', views.paylasimdabulun, name='paylasimdabulun'),
    url(r'^ajax/load/$', views.load_counties, name='ajax_load_counties'),
    url(r'^$', views.home, name='home'),
    url(r'^register/', views.register, name='register'),
    url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
    url(r'^ajax/validate_email/$', views.validate_email, name='validate_email'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^acil/', views.acil, name='acil'),
    url(r'^conversation$', broadcast),
    url(r'^conversations/$', conversations),
    url(r'^conversations/(?P<id>[-\w]+)/delivered$',delivered),
    url(r'^chat/', views.chat, name='chat'),
    path("inbox/", InboxView.as_view()),
    re_path(r"^messages/(?P<username>[\w.@+-]+)/$", ThreadView.as_view()),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kanbagisapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User

from django.db.models import Q

class RegisterPageSlide(models.Model):
    header = models.CharField(max_length=32)
    image = models.FileField(upload_to='', help_text="640x426")
    created_at = models.DateTimeField(blank=True, null=True,auto_now_add=True)

    def __str__(self):
        return self.header

class province(models.Model):
    province_id = models.AutoField(primary_key=True)
    province_name = models.CharField(max_length=100,help_text="İl :")

    def __str__(self):
        return self.province_name

class county(models.Model):
    county_id = models.AutoField(primary_key=True)
    county_name = models.CharField(max_length=100,help_text="İlçe :")
    province_id = models.ForeignKey(province, on_delete=models.CASCADE, help_text="İl :")

    def __str__(self):
        return  self.county_name

class blood_group(models.Model):
    blood_id = models.AutoField(primary_key=True)
    blood_name = models.CharField(max_length=32,help_text="Kan Grubu :")

    def __str__(self):
        return self.blood_name

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, null=True, max_length=20)
    blood_group = models.ForeignKey(blood_group, on_delete=models.CASCADE,blank=True, null=True,help_text="Kan Grubu :")
    province = models.ForeignKey(province, on_delete=models.CASCADE,blank=True, null=True,help_text="İl :")
    county = models.ForeignKey(county, on_delete=models.CASCADE,blank=True, null=True,help_text="İlçe :")
    birth_date = models.DateTimeField(blank=True, null=True,default=datetime.now)
    created_at = models.DateTimeField(blank=True, null=True,auto_now_add = True)
    updated_at = models.DateTimeField(blank=True, null=True,auto_now = True)
    confirmed = models.BooleanField(default=False, help_text="Onaylı kullanıcı")
    privacy = models.BooleanField(default=False, help_text="Gizlilik")
    informed = models.BooleanField(default=False, help_text="Bilgili kullanıcı")

    def __str__(self):
        return self.user.username

BLOOD_CHOICES = (
   ('kan arıyor', 'Kan arıyorum'),
   ('kan veriyor', 'Kan veriyorum')
)

class blood_share(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    blood_group = models.ForeignKey(blood_group, on_delete=models.CASCADE,help_text="Kan Grubu :")
    province = models.ForeignKey(province, on_delete=models.CASCADE,help_text="İl :")
    county = models.ForeignKey(county, on_delete=models.CASCADE,help_text="İlçe :")
    date_range = models.DateTimeField(default=datetime.now,help_text="Tarih aralığı :")
    searching_reason = models.TextField(max_length=700,editable = True,help_text="Kan arama nedeni :")
    contact_name = models.CharField(max_length=32,help_text="İletişim ismi :")
    contact_number = models.CharField(max_length=20,help_text="İletişim numarası :")
    choice = models.CharField(choices=BLOOD_CHOICES,max_length=32)
    sharing_date = models.DateTimeField(blank=True, null=True,auto_now_add = True)
    updated_at = models.DateTimeField(blank=True, null=True,auto_now = True)
    favorite = models.ManyToManyField(User, related_name='favorite', blank=True)

    def __str__(self):
        return self.user.username

NOTIFICATION_TYPE = (
    ('info', 'Bilgi'),
    ('success', 'Başarılı'),
    ('alert', 'Uyarı')
)

class ProfileNotification(models.Model):
    receiver = models.ForeignKey(User, on_delete=models.CASCADE)
    header = models.CharField(max_length=32)
    body = models.TextField(max_length=500, editable = True)
    footer = models.CharField(max_length=32)
    choice = models.CharField(choices=NOTIFICATION_TYPE,max_length=32)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.header
        # return ("{0} {1} {2}".format(self.receiver, self.header, self.choice))

class HomeRightInformation(models.Model):
    content = models.TextField(max_length=150)
    written_by = models.CharField(max_length=16)
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

class feedback(models.Model):
    feedback_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=32)
    message = models.TextField(max_length=700,editable = True)
    created_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.name

class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name="sender")
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name="receiver")
    message = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.message

class Conversation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.CharField(blank=True, null=True, max_length=225)
    status = models.CharField(blank=True, null=True, max_length=225)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username


class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_username): # get_or_create
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) & Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) & Q(second__username=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user.__class__
            user2 = Klass.objects.get(username=other_username)
            if user != user2:
                obj = self.model(
                        first=user,
                        second=user2
                    )
                obj.save()
                return obj, True
            return None, False

class Thread(models.Model):
    first = models.ForeignKey(User, on_delete=models.CASCADE, related_name="chat_thread_first")
    second = models.ForeignKey(User, on_delete=models.CASCADE, related_name="chat_thread_second")
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = ThreadManager()

    @property
    def room_group_name(self):
        return f'Oda-{self.id}'

    def broadcast(self, msg=None):
        if msg is not None:
            broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
            return True
        return False

    def __str__(self):
        return str(self.first) if self.first else ''

class ChatMessage(models.Model):
    thread = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='sender')
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message

kanbagisapp/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import province, county, blood_group, UserProfile, blood_share, feedback, Message, HomeRightInformation


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=False,max_length=30)
    last_name = forms.CharField(required=False,max_length=50)

    class Meta:
        model = User
        fields = ('username','email','first_name','last_name','password1','password2')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email zaten mevcut")
        return email

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phone','blood_group','province','county','birth_date', 'privacy')

    def  __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['county'].queryset = county.objects.none()

        if 'province' in self.data:
            try:
                province_id = int(self.data.get('province'))
                self.fields['county'].queryset = county.objects.filter(province_id=province_id).order_by('county_name')
            except (ValueError, TypeError):
                pass # invalid input from the user; ignore and fallback to empty County queryset

class UserRegistrationUpdateForm(forms.ModelForm):
    first_name = forms.CharField(required=True,max_length=30)
    last_name = forms.CharField(required=True,max_length=50)

    class Meta:
        model = User
        fields = ('username','first_name','last_name')

class UserProfileUpdateForm(forms.ModelForm):
    phone = forms.CharField(required=True,max_length=30)
    class Meta:
        model = UserProfile
        fields = ('phone','blood_group','province','county','birth_date', 'privacy')

class provinceForm(forms.ModelForm):
    class Meta:
        model = province
        fields = ("province_id","province_name")

class countyForm(forms.ModelForm):
    class Meta:
        model = county
        fields = ("county_id","county_name","province_id")

class blood_groupForm(forms.ModelForm):
    class Meta:
        model = blood_group
        fields = ("blood_id","blood_name")

class feedbackForm(forms.ModelForm):
    class Meta:
        model = feedback
        fields = ("name","message")

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ("message",)

class HomeRightInformationForm(forms.ModelForm):
    class Meta:
        model = HomeRightInformation
        fields = ("content","written_by")

BLOOD_CHOICES = (
   ('kan arıyor', 'Kan arıyorum'),
   ('kan veriyor', 'Kan veriyorum')
)

class blood_shareForm(forms.ModelForm):
    choice = forms.ChoiceField(choices=BLOOD_CHOICES, widget=forms.RadioSelect())
    class Meta:
        model = blood_share
        fields = ("blood_group","province","county","date_range","searching_reason","contact_name","contact_number","choice")

    def  __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['county'].queryset = county.objects.none()

        if 'province' in self.data:
            try:
                province_id = int(self.data.get('province'))
                self.fields['county'].queryset = county.objects.filter(province_id=province_id).order_by('county_name')
            except (ValueError, TypeError):
                pass # invalid input from the user; ignore and fallback to empty County queryset


class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )

kanbagisapp/templates/chat/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Kan Bağışı | Gerçek zamanlı mesajlaşma</title>
    <link href="{% static 'images/kan_icon.png' %}" rel="icon">
    <!--===============================================================================================-->
      <link rel="stylesheet" type="text/css" href="{% static 'css/loaderstyle.css' %}">
    <!--===============================================================================================-->
      <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
    {% include 'chat/css.html' %}
</head>
<body>

  <!-- LOADER -->
    <div id="preloader">
    	<div class="preloader pulse">
    		<i class="fa fa-heartbeat" aria-hidden="true"></i>
    	</div>
    </div>

<div class='container'>
    <div class='row border-bottom my-3 py-3'>
        <div class='col-md-10'>
            <h1 class='p-0 m-0'>Gerçek Zamanlı Mesajlaş</h1>
            <!--{{ thread.room_group_name }}-->
        </div>
        <div class='col-md-2'>
            ({{ thread.room_group_name }})
        </div>
    </div>
{% block content %}
{% endblock %}
</div>


{% include 'chat/js.html' %}
{% block script %}
{% endblock %}

</body>
</html>

kanbagisapp/templates/chat/css.html
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">

kanbagisapp/templates/chat/inbox.html
{% extends "chat/base.html" %}

{% block content %}


{% endblock %}

kanbagisapp/templates/chat/js.html
 <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script
  src="//code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="//stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

kanbagisapp/templates/chat/thread.html
{% extends "chat/base.html" %}
{% load staticfiles %}

{% block content %}
<h3>{% if user != object.first %}{{ object.first }}{% else %}{{ object.second }}{% endif %} ile mesajlaş</h3>

<ul id='chat-items'>
  {% for chat in object.chatmessage_set.all %}
    <li><b>{{ chat.user }}</b>: {{ chat.message }}</li>
  {% endfor %}
</ul>

<form id='form' method='POST'> {% csrf_token %}
  <input type="hidden" id="myUsername" value="{{ user.username }}" />
  Mesajınız
  <p>{{ form.message }}</p>
  <button class="btn btn-primary" type="submit">Gönder</button>
</form>

{% endblock %}

{% block script %}
<script src="{% static 'js/custom.js' %}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/
reconnecting-websocket.js"></script>
<script>
// websocket scripts
//console.log(window.location)
var loc = window.location
var formData = $("#form")
var msgInput = $("#id_message")
var chatHolder = $("#chat-items")
var me = $("#myUsername").val()

var wsStart = 'ws://'
if (loc.protocol == 'https:'){
  wsStart = 'wss://'
}
var endpoint = wsStart + loc.host + loc.pathname
var socket = new WebSocket(endpoint)

socket.onmessage = function(e){
  console.log("message", e)
  var chatDataMsg = JSON.parse(e.data)
  chatHolder.append("<li>" + "<b>" + chatDataMsg.username + "</b>: " + chatDataMsg.message + "</li>")
}
socket.onopen = function(e){
  console.log("open", e)
  formData.submit(function(event){
    event.preventDefault()
    var msgText = msgInput.val()
    // chatHolder.append("<li>" + "<b>" + me + "</b>: " + msgText + "</li>")
    // var formDataSerialized = formData.serialize()
    var finalData = {
      'message': msgText
    }

    socket.send(JSON.stringify(finalData))
    formData[0].reset()
  })
}
socket.onerror = function(e){
  console.log("error", e)
}
socket.onclose = function(e){
  console.log("close", e)
}

</script>
{% endblock %}