kanbagis/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from kanbagisapp import views as kanbagisapp_views
from django.conf.urls import handler404, handler500

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('kanbagisapp.urls'))
]


admin.site.site_header = 'Kan Bağış Admin'
admin.site.index_title = 'Kan Bağışı'  
admin.site.site_title = 'Admin Sayfası'

kanbagisapp/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib import admin
from django.contrib.auth import views as auth_views
from kanbagisapp.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path
from .views import ThreadView, InboxView

urlpatterns = [
    url('^', include('django.contrib.auth.urls')),
    url(r'^home', views.home, name='home'),
    url(r'^icerik/(?P<id>\d+)/$', views.icerik, name='icerik'),
    url(r'^about', views.hakkimizda, name='hakkimizda'),
    url(r'^login/', auth_views.login, name='login'),
    url(r'^profile/(?P<username>\w+)/$', views.profile, name='profile'),
    url(r'^share', views.paylasimdabulun, name='paylasimdabulun'),
    url(r'^ajax/load/$', views.load_counties, name='ajax_load_counties'),
    url(r'^$', views.home, name='home'),
    url(r'^register/', views.register, name='register'),
    url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
    url(r'^ajax/validate_email/$', views.validate_email, name='validate_email'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^acil/', views.acil, name='acil'),
    url(r'^conversation$', broadcast),
    url(r'^conversations/$', conversations),
    url(r'^conversations/(?P<id>[-\w]+)/delivered$',delivered),
    url(r'^chat/', views.chat, name='chat'),
    path("inbox/", InboxView.as_view()),
    re_path(r"^messages/(?P<username>[\w.@+-]+)/$", ThreadView.as_view()),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kanbagisapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User

from django.db.models import Q

class RegisterPageSlide(models.Model):
    header = models.CharField(max_length=32)
    image = models.FileField(upload_to='', help_text="640x426")
    created_at = models.DateTimeField(blank=True, null=True,auto_now_add=True)

    def __str__(self):
        return self.header

class province(models.Model):
    province_id = models.AutoField(primary_key=True)
    province_name = models.CharField(max_length=100,help_text="İl :")

    def __str__(self):
        return self.province_name

class county(models.Model):
    county_id = models.AutoField(primary_key=True)
    county_name = models.CharField(max_length=100,help_text="İlçe :")
    province_id = models.ForeignKey(province, on_delete=models.CASCADE, help_text="İl :")

    def __str__(self):
        return  self.county_name

class blood_group(models.Model):
    blood_id = models.AutoField(primary_key=True)
    blood_name = models.CharField(max_length=32,help_text="Kan Grubu :")

    def __str__(self):
        return self.blood_name

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, null=True, max_length=20)
    blood_group = models.ForeignKey(blood_group, on_delete=models.CASCADE,blank=True, null=True,help_text="Kan Grubu :")
    province = models.ForeignKey(province, on_delete=models.CASCADE,blank=True, null=True,help_text="İl :")
    county = models.ForeignKey(county, on_delete=models.CASCADE,blank=True, null=True,help_text="İlçe :")
    birth_date = models.DateTimeField(blank=True, null=True,default=datetime.now)
    created_at = models.DateTimeField(blank=True, null=True,auto_now_add = True)
    updated_at = models.DateTimeField(blank=True, null=True,auto_now = True)
    confirmed = models.BooleanField(default=False, help_text="Onaylı kullanıcı")
    privacy = models.BooleanField(default=False, help_text="Gizlilik")
    informed = models.BooleanField(default=False, help_text="Bilgili kullanıcı")

    def __str__(self):
        return self.user.username

BLOOD_CHOICES = (
   ('kan arıyor', 'Kan arıyorum'),
   ('kan veriyor', 'Kan veriyorum')
)

class blood_share(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    blood_group = models.ForeignKey(blood_group, on_delete=models.CASCADE,help_text="Kan Grubu :")
    province = models.ForeignKey(province, on_delete=models.CASCADE,help_text="İl :")
    county = models.ForeignKey(county, on_delete=models.CASCADE,help_text="İlçe :")
    date_range = models.DateTimeField(default=datetime.now,help_text="Tarih aralığı :")
    searching_reason = models.TextField(max_length=700,editable = True,help_text="Kan arama nedeni :")
    contact_name = models.CharField(max_length=32,help_text="İletişim ismi :")
    contact_number = models.CharField(max_length=20,help_text="İletişim numarası :")
    choice = models.CharField(choices=BLOOD_CHOICES,max_length=32)
    sharing_date = models.DateTimeField(blank=True, null=True,auto_now_add = True)
    updated_at = models.DateTimeField(blank=True, null=True,auto_now = True)
    favorite = models.ManyToManyField(User, related_name='favorite', blank=True)

    def __str__(self):
        return self.user.username

NOTIFICATION_TYPE = (
    ('info', 'Bilgi'),
    ('success', 'Başarılı'),
    ('alert', 'Uyarı')
)

class ProfileNotification(models.Model):
    receiver = models.ForeignKey(User, on_delete=models.CASCADE)
    header = models.CharField(max_length=32)
    body = models.TextField(max_length=500, editable = True)
    footer = models.CharField(max_length=32)
    choice = models.CharField(choices=NOTIFICATION_TYPE,max_length=32)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.header
        # return ("{0} {1} {2}".format(self.receiver, self.header, self.choice))

class HomeRightInformation(models.Model):
    content = models.TextField(max_length=150)
    written_by = models.CharField(max_length=16)
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

class feedback(models.Model):
    feedback_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=32)
    message = models.TextField(max_length=700,editable = True)
    created_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.name

class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name="sender")
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name="receiver")
    message = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.message

class Conversation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.CharField(blank=True, null=True, max_length=225)
    status = models.CharField(blank=True, null=True, max_length=225)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username


class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_username): # get_or_create
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) & Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) & Q(second__username=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user.__class__
            user2 = Klass.objects.get(username=other_username)
            if user != user2:
                obj = self.model(
                        first=user,
                        second=user2
                    )
                obj.save()
                return obj, True
            return None, False

class Thread(models.Model):
    first = models.ForeignKey(User, on_delete=models.CASCADE, related_name="chat_thread_first")
    second = models.ForeignKey(User, on_delete=models.CASCADE, related_name="chat_thread_second")
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = ThreadManager()

    @property
    def room_group_name(self):
        return f'Oda-{self.id}'

    def broadcast(self, msg=None):
        if msg is not None:
            broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
            return True
        return False

    def __str__(self):
        return str(self.first) if self.first else ''

class ChatMessage(models.Model):
    thread = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='sender')
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message

kanbagisapp/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import province, county, blood_group, UserProfile, blood_share, feedback, Message, HomeRightInformation


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=False,max_length=30)
    last_name = forms.CharField(required=False,max_length=50)

    class Meta:
        model = User
        fields = ('username','email','first_name','last_name','password1','password2')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email zaten mevcut")
        return email

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phone','blood_group','province','county','birth_date', 'privacy')

    def  __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['county'].queryset = county.objects.none()

        if 'province' in self.data:
            try:
                province_id = int(self.data.get('province'))
                self.fields['county'].queryset = county.objects.filter(province_id=province_id).order_by('county_name')
            except (ValueError, TypeError):
                pass # invalid input from the user; ignore and fallback to empty County queryset

class UserRegistrationUpdateForm(forms.ModelForm):
    first_name = forms.CharField(required=True,max_length=30)
    last_name = forms.CharField(required=True,max_length=50)

    class Meta:
        model = User
        fields = ('username','first_name','last_name')

class UserProfileUpdateForm(forms.ModelForm):
    phone = forms.CharField(required=True,max_length=30)
    class Meta:
        model = UserProfile
        fields = ('phone','blood_group','province','county','birth_date', 'privacy')

class provinceForm(forms.ModelForm):
    class Meta:
        model = province
        fields = ("province_id","province_name")

class countyForm(forms.ModelForm):
    class Meta:
        model = county
        fields = ("county_id","county_name","province_id")

class blood_groupForm(forms.ModelForm):
    class Meta:
        model = blood_group
        fields = ("blood_id","blood_name")

class feedbackForm(forms.ModelForm):
    class Meta:
        model = feedback
        fields = ("name","message")

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ("message",)

class HomeRightInformationForm(forms.ModelForm):
    class Meta:
        model = HomeRightInformation
        fields = ("content","written_by")

BLOOD_CHOICES = (
   ('kan arıyor', 'Kan arıyorum'),
   ('kan veriyor', 'Kan veriyorum')
)

class blood_shareForm(forms.ModelForm):
    choice = forms.ChoiceField(choices=BLOOD_CHOICES, widget=forms.RadioSelect())
    class Meta:
        model = blood_share
        fields = ("blood_group","province","county","date_range","searching_reason","contact_name","contact_number","choice")

    def  __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['county'].queryset = county.objects.none()

        if 'province' in self.data:
            try:
                province_id = int(self.data.get('province'))
                self.fields['county'].queryset = county.objects.filter(province_id=province_id).order_by('county_name')
            except (ValueError, TypeError):
                pass # invalid input from the user; ignore and fallback to empty County queryset


class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )

kanbagisapp/templates/kanbagisapp/error_404.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <title>Sayfa Bulunamadı</title>
  <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>

<h2 align=center>Üzgünüz, bu sayfaya ulaşılamıyor.</h2>
<p align=center>Tıkladığın bağlantı bozuk olabilir veya sayfa kaldırılmış olabilir. <a href="/home/">Ana Sayfa</a>'ya geri dön.</p>

</body>
</html>

kanbagisapp/templates/kanbagisapp/error_500.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <title>İç Sunucu Hatası</title>
</head>

<body>

<h2 align=center>Bu sayfayı gördüğünüz için çok üzgünüz.</h2>
<p align=center>Sunucuyla bağlı bir hata oluştu. En kısa zamanda düzeltilecek.</a></p>
<h1 align=center>&#9785;</h1>
</body>
</html>

kanbagisapp/templates/kanbagisapp/load.html
<option value="">İlçe</option>
{% for county in counties %}
<option value="{{county.county_id}}">{{county.county_name}}</option>
{% endfor %}

kanbagisapp/templates/kanbagisapp/paylasimdabulun.html
{% load staticfiles %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Kan Bağışı | Paylaşımda Bulun</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">
  <link href="{% static 'images/kan_icon.png' %}" rel="icon">
  <link href="{% static 'img/kan.png' %}" rel="apple-touch-icon">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/venobox.css' %}">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/anastyle.css' %}">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/loaderstyle.css' %}">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/tabs.css' %}">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/share.css' %}"><!--mumkun mertebe paylasim tasarimini degis ve bu css-i qaldir-->
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/home-slide.css' %}">
<!--===============================================================================================-->
  <style>
  @media only screen and (max-width: 768px) {
    /* For mobile phones: */
    [class*="col-"] {
      width: 100%;
    }
  }
    ::selection {
      color: white;
      background: red;
    }
    .isa_warning {
      color: #4D5656;
      background-color: #E5E7E9;
			width: 100%;
			margin-bottom: 10px;
      padding:8px;
      border-radius: 8px;
    }
    .button_outline{
      outline:none !important;
    }
    acil{
      color: white;
      background-color: red;
      border-radius: 5px;
      padding: 3px;
    }
    .card{
      box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
      border: 1px solid;
      border-color: #D1D1D1;
      padding: 10px 16px;
      margin-bottom: 10px;
    }
  </style>
</head>
<body>
<!-- LOADER -->
  <div id="preloader">
  	<div class="preloader pulse">
  		<i class="fa fa-heartbeat" aria-hidden="true"></i>
  	</div>
  </div>


  <header id="header">
    <div class="container">
      <div id="logo" class="pull-left">
        <a href="/home/" class="scrollto"><img src="{% static 'images/med.png' %}" ></a>
      </div>
      <nav id="nav-menu-container">
        <ul class="nav-menu">
          <li><a href="/home/">Ana Sayfa</a></li>
          <li><a href="/about/">Hakkımızda</a></li>
          <li class="menu-active"><a href="/share/">Paylaşımda bulun</a></li>
          {% if user.is_authenticated %}
          <li class="buy-tickets"><a href="{% url 'profile' username=request.user %}">Profil</a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </header>

  <div class="container-fluid" style="margin-top: 10%">
    <div class="row">
      <div class="col-md-3" id="leftbox">
        <div class="jumbotron">
          <h4>Reklam Alanı</h4>
          <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling
              extra
              attention to featured content or information.</p>
        </div>
      </div>


      <div class="col-md-6" id="middlebox">
        {% if user.is_authenticated %}
        <div class="well kayitTamamlandi">
          <h6 style="padding-left:2%; font-size:14px">Paylasimda bulunmak hakkinda bilgilendirme, kurallar kismi.</h6>
          <h6 style="padding-left:2%; font-size:14px">Hesabınızı "Acil kayıt" ile oluşturduysanız kan bağışında bulunamazsınız.</h6>
        </div><br>

        <form method="POST" id="blood_shareForm" data-counties-url="{% url 'ajax_load_counties' %}" action="/share/">
        {% csrf_token %}
        <div class="card">
            <div class="card-body">
              <div class="form-row">
                  <div class="name">Kan grubu</div>
                  <div class="value">
                      {{form.blood_group}}
                  </div>
              </div>
              <div class="form-row">
                  <div class="name">İl</div>
                  <div class="value">
                      {{form.province}}
                  </div>
              </div>
              <div class="form-row">
                  <div class="name">İlçe</div>
                  <div class="value">
                      {{form.county}}
                  </div>
              </div>
              <div class="form-row">
                  <div class="name">Tarih aralığı</div>
                  <div class="value">
                      <input class="input--style-6" type="text" name="date_range" placeholder="12/12/2020 06:58:59">
                  </div>
              </div>
              <div class="form-row">
                  <div class="name">Kan arama nedeni</div>
                  <div class="value">
                      <div class="input-group">
                          <textarea class="textarea--style-6" name="searching_reason" placeholder="Kan arama nedeniniz.."></textarea>
                      </div>
                  </div>
              </div>
              <div class="form-row">
                  <div class="name">İletişim ismi</div>
                  <div class="value">
                      <input class="input--style-6" type="text" name="contact_name">
                  </div>
              </div>
              <div class="form-row">
                  <div class="name">İletişim numarası</div>
                  <div class="value">
                      <input class="input--style-6" type="text" name="contact_number">
                  </div>
              </div>
              <div align="center">
                <label>
                  <input type="radio" class="option-input radio button_outline" name="choice" value="kan arıyor"/>
                  Kan arıyorum
                </label>
                {% if not user.first_name %}
                <label>
                  <input type="radio" class="option-input radio button_outline" disabled name="choice" value="kan veriyor"/>
                  <span style="color: #818182;" data-toggle="modal" data-target="#exampleModal">Kan veriyorum</span>
                  <!--popup modal START-->
                  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                          <h5 class="modal-title" id="exampleModalLabel">Bilgilendirme..</h5>
                        </div>
                        <div class="modal-body">
                          <acil>Acil kayıt</acil> ile oluşturulmuş hesapla kan bağışında bulunamazsınız.
                          <details>
                            <summary class="button_outline">Acil kayıtın amaçlarını görmek için tıklayın.</summary>
                            <li>ornekleme</li>
                            <li>olabilir</li>
                            <li>meselaa</li>
                          </details>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-primary" data-dismiss="modal">Kapat</button>
                        </div>
                      </div>
                    </div>
                  </div>
                  <!--popup modal END-->
                </label>
                {% else %}
                <label>
                  <input type="radio" class="option-input radio button_outline" name="choice" value="kan veriyor"/>
                  Kan veriyorum
                </label>
                {% endif %}
              </div>
            </div>
          <div class="card-footer">
              <br><button class="btn btn--radius-2 btn--blue-2 button_outline" type="submit">Paylaşımda bulun</button><br><br>
          </div>
        </div>
        </form>
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script>
          $("#id_province").change(function(){
            var url = $("#blood_shareForm").attr("data-counties-url"); // get the url of the 'load_counties'view
            var provinceId = $(this).val();   // get the selected province id from the HTML input
            $.ajax({                          // initialize an AJAX request
              url: url,                       // set the url of the request (http://127.0.0.1:8000/ajax/load/)
              data: {
                'province': provinceId        // add the province id to the GET parameters
              },
              success: function(data){        // 'data' is the return of the 'load_counties' view function
                $("#id_county").html(data);   // replace the contents of the county input with the data that came
              }
            });
          });
        </script>
        {% else %}
        <div class="card" align="center">
          <div class="card-header" style="background-color:white;">
            <h5><i class="fa fa-3x fa-sign-in" aria-hidden="true"></i></h5>
          </div>
          <!--<div class="card-header">
            <h5><i class="fa fa-warning"></i></h5>
          </div>-->
          <p>Siteye kayıt olmadan paylaşımda bulunamazsınız.</p>
          <footer class="blockquote-footer"><a href="/register/">Kayıt Ol</a> yada <a href="/login/">Giriş Yap</a></footer>
        </div>
        {% endif %}
      </div>

      <div class="col-md-3" id="rightbox">
        {% if user.is_authenticated %}
          <div class="slideshow-container">
            {% for right in homeRightInformation %}
              {% if right.created_at|naturalday == "bugün" %}
                <div class="mySlides">
                  <q>{{ right.content }}</q>
                  <p class="author">- {{ right.written_by }}</p>
                </div>
              {% elif right.created_at|naturalday != "bugün" %}
                <div class="mySlides">
                  <q></q>
                  <p class="author">- </p>
                </div>
              {% endif %}
            {% empty %}
                <div class="mySlides">
                  <q></q>
                  <p class="author">- </p>
                </div>
            {% endfor %}

            <a class="prev" onclick="plusSlides(-1)">❮</a>
            <a class="next" onclick="plusSlides(1)">❯</a>
          </div>
          <div class="dot-container"></div>
        {% else %}
          <div class="slideshow-container">
            <div class="mySlides">
              <q></q>
              <p><a href="/register/">Kayıt Ol</a> yada <a href="/login/">Giriş Yap</a></p>
            </div>
            <a class="prev" onclick="plusSlides(-1)">❮</a>
            <a class="next" onclick="plusSlides(1)">❯</a>
          </div>
          <div class="dot-container"></div>
        {% endif %}
      </div>
    </div>
  </div>




<!--===============================================================================================-->
	<script src="{% static 'js/jquery.min.js' %}"></script>
<!--===============================================================================================-->
  <script src="{% static 'js/wow.min.js' %}"></script>
<!--===============================================================================================-->
  <script src="{% static 'js/venobox.min.js' %}"></script>
<!--===============================================================================================-->
  <script src="{% static 'js/custom.js' %}"></script>
<!--===============================================================================================-->
  <script src="{% static 'js/mainy.js' %}"></script>
<!--===============================================================================================-->
  <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script><!--=popup-->
<!--===============================================================================================-->
  <script src="{% static 'js/home-slide.js' %}"></script>
<!--===============================================================================================-->
</body>
</html>